"""add_zerodha_fields_to_positions

Revision ID: c0b2434c3153
Revises: c5537ee07178
Create Date: 2025-11-27 13:25:02.966256+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b2434c3153'
down_revision: Union[str, None] = 'c5537ee07178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('paper_positions', sa.Column('tradingsymbol', sa.String(), nullable=True))
    op.add_column('paper_positions', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('paper_positions', sa.Column('product', sa.String(), nullable=True))
    op.add_column('paper_positions', sa.Column('buy_qty', sa.Integer(), nullable=True))
    op.add_column('paper_positions', sa.Column('sell_qty', sa.Integer(), nullable=True))
    op.add_column('paper_positions', sa.Column('ltp', sa.Float(), nullable=True))
    op.add_column('paper_positions', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('paper_positions', sa.Column('day_change', sa.Float(), nullable=True))
    op.add_column('paper_positions', sa.Column('day_change_percentage', sa.Float(), nullable=True))
    op.add_column('paper_positions', sa.Column('multiplier', sa.Integer(), nullable=True))
    op.add_column('paper_positions', sa.Column('var_margin', sa.Float(), nullable=True))
    
    # Populate default values for existing rows
    op.execute("UPDATE paper_positions SET tradingsymbol = symbol WHERE tradingsymbol IS NULL")
    op.execute("UPDATE paper_positions SET exchange = 'NFO' WHERE exchange IS NULL")
    op.execute("UPDATE paper_positions SET product = 'MIS' WHERE product IS NULL")
    op.execute("UPDATE paper_positions SET buy_qty = CASE WHEN quantity > 0 THEN quantity ELSE 0 END WHERE buy_qty IS NULL")
    op.execute("UPDATE paper_positions SET sell_qty = CASE WHEN quantity < 0 THEN ABS(quantity) ELSE 0 END WHERE sell_qty IS NULL")
    op.execute("UPDATE paper_positions SET ltp = current_price WHERE ltp IS NULL")
    op.execute("UPDATE paper_positions SET pnl = COALESCE(realized_pnl, 0) + COALESCE(unrealized_pnl, 0) WHERE pnl IS NULL")
    op.execute("UPDATE paper_positions SET multiplier = 1 WHERE multiplier IS NULL")
    
    # Make required columns non-nullable
    op.alter_column('paper_positions', 'tradingsymbol', nullable=False)
    op.alter_column('paper_positions', 'exchange', nullable=False)
    op.alter_column('paper_positions', 'product', nullable=False)
    op.alter_column('paper_positions', 'buy_qty', nullable=False)
    op.alter_column('paper_positions', 'sell_qty', nullable=False)
    op.alter_column('paper_positions', 'pnl', nullable=False)
    op.alter_column('paper_positions', 'multiplier', nullable=False)
    
    # Create index
    op.create_index(op.f('ix_paper_positions_tradingsymbol'), 'paper_positions', ['tradingsymbol'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_tradingsymbol'), table_name='paper_positions')
    op.drop_column('paper_positions', 'var_margin')
    op.drop_column('paper_positions', 'multiplier')
    op.drop_column('paper_positions', 'day_change_percentage')
    op.drop_column('paper_positions', 'day_change')
    op.drop_column('paper_positions', 'pnl')
    op.drop_column('paper_positions', 'ltp')
    op.drop_column('paper_positions', 'sell_qty')
    op.drop_column('paper_positions', 'buy_qty')
    op.drop_column('paper_positions', 'product')
    op.drop_column('paper_positions', 'exchange')
    op.drop_column('paper_positions', 'tradingsymbol')
    # ### end Alembic commands ###
