"""Rename metadata to action_metadata in AdminAction

Revision ID: f91e0ee05c5e
Revises: af25a8ed6be3
Create Date: 2025-12-02 15:55:59.267734+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f91e0ee05c5e'
down_revision: Union[str, None] = 'af25a8ed6be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_admin_actions_action_type', table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_user_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_created_at', table_name='admin_actions')
    op.drop_index('ix_admin_actions_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_target_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_target_type', table_name='admin_actions')
    op.drop_table('admin_actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_actions_pkey')
    )
    op.create_index('ix_admin_actions_target_type', 'admin_actions', ['target_type'], unique=False)
    op.create_index('ix_admin_actions_target_id', 'admin_actions', ['target_id'], unique=False)
    op.create_index('ix_admin_actions_id', 'admin_actions', ['id'], unique=False)
    op.create_index('ix_admin_actions_created_at', 'admin_actions', ['created_at'], unique=False)
    op.create_index('ix_admin_actions_admin_user_id', 'admin_actions', ['admin_user_id'], unique=False)
    op.create_index('ix_admin_actions_action_type', 'admin_actions', ['action_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'TOURNAMENT', 'PRIZE', 'ADMIN', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###
