"""Add admin features: AdminAction and Notification models

Revision ID: af25a8ed6be3
Revises: c0b2434c3153
Create Date: 2025-12-02 15:50:05.312834+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af25a8ed6be3'
down_revision: Union[str, None] = 'c0b2434c3153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
